= About {prod}
This project is a proof of concept.

{prod} is a {cdi} (CDI) framework. {prod} implements CDI specifications and is inspired by the link:http://erraiframework.org/[Errai framework] created by {rh}. Errai is only GWT2-compatible, while {prod} uses J2CL and has no GWT2 dependencies.

{prod} is based on annotation processors code generation and supports the following features among others:

* CDI stereotypes
* HTML templates
* Data Binding library

This link:https://crysknife.cloud.unispace.io/[demo page] shows how {prod} can be used on a simple page compiled with J2CL ({mvn-plgn}).

== Under the hood
{prod} was inspired by {gwt} and Errai and relies on several other technologies (and various GWT comunity projects).

GWT:: An open-source development toolkit that is built around a Java-to-JavaScript compiler. GWT allows to develop and optimize high-performance web applications. &mdash; http://www.gwtproject.org/
Errai:: A GWT-based framework developed by {rh}. It allows to build rich web applications using Java. &mdash; http://erraiframework.org/
J2CL:: Google's Java-to-Closure-JavaScript transpiler allows to compile Java to Closure-style JavaScript. &mdash; https://github.com/google/j2cl
CDI:: A Dependency Injection framework for Java. &mdash; http://cdi-spec.org/
Closure Compiler:: Google's Closure Compiler parses and optimizes JavaScript code making it run faster. &mdash; https://developers.google.com/closure/compiler
{mvn-plgn-full}:: Vertispan's Maven Plugin for J2CL helps to build GWT projects with Maven. &mdash; https://github.com/Vertispan/j2clmavenplugin
